### ISSUE TITLE
CTR to use Data Flow Parser Dependency.

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud-task-app-starters/composed-task-runner#16] opened 2017-06-13 15:29 UTC
CTR needs to be updated to use the extracted DataFlow Parser dependency.  

https://github.com/spring-cloud-task-app-starters/app-starters-release/issues/37

**Comment by sabbyanandan** [comment] 2017-09-19 16:46
This is not required anymore. Duplicate of spring-cloud-task-app-starters/composed-task-runner#18.

**Closed as completed by sabbyanandan** 2017-09-19 16:46 UTC
Labels: duplicate
