### ISSUE TITLE
Tasks could notify status by message instead of using DB 

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud-task-app-starters/composed-task-runner#4] opened 2017-03-23 19:41 UTC
Another future optimization would be to allow the tasks to notify status by message instead of using DB . Obviously it would be something that the task developer would need to do, but would be more efficient.

**Comment by jvmlet** [comment] 2018-03-12 14:16
+1 for this feature. Messaging middleware is much  more scalable than RDB and this is `push`, not `pull`. Also, the cloud task  already supports publishing to underlying middleware via `org.springframework.cloud:spring-cloud-starter-stream-rabbit/kafka`

**Comment by mminella** [comment] 2018-03-12 14:44
@jvmlet We don't disagree from an architecture perspective.  The issue is the dependency management.  In order for this to work, every app the composed task launcher runs and the composed task launcher itself would require Spring Cloud Stream dependencies including the same binder on the classpath.  Not a simple requirement.

**Comment by jvmlet** [comment] 2018-03-12 23:10
Agreed, but we have our custom task starter  for every task app developed in our company, so this requirement is easy to satisfy.. I've also repackaged the CTR app to bundle the binder implementation. It's easier than it sounds...

**Comment by sabbyanandan** [comment] 2020-04-02 17:13
Closing this as not applicable anymore.

**Closed as completed by sabbyanandan** 2020-04-02 17:13 UTC
