### ISSUE TITLE
On next execution, CTR proceeds from  previously  failed step  

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud-task-app-starters/composed-task-runner#23] opened 2017-11-29 14:03 UTC
Hello
I've the composed tasks `myFailedTask` with 2 steps and one of them is configured to fail all the time :
`<mf1: sampleTask --fail=true --custom-argument=m || sampleTask>`
On first run, the job runs with `run.id` equals  1 and  and `mf1` is reported as failed , BTW, the UI shows the exit code of `myFailedTask` as 0 , isn't is a bug ?
![image](https://user-images.githubusercontent.com/6664858/33378474-928f8fb8-d51d-11e7-881d-bb9dea6b4808.png)
 
Next time I run the CTR, it skips   the `sampleTask` and runs the `mf1` with `run.id` equals to 1 again :

`2017-11-29 15:30:30.146  INFO 11604 --- [ taskExecutor-2] o.s.batch.core.job.SimpleStepHandler     : Step already complete or not restartable, so no action to execute: StepExecution: id=97, version=3, name=myFailedTask-sampleTask_0, status=COMPLETED, exitStatus=COMPLETED, readCount=0, filterCount=0, writeCount=0 readSkipCount=0, writeSkipCount=0, processSkipCount=0, commitCount=1, rollbackCount=0, exitDescription=
`

I'm executing the CTR using the `httpclient` transformer deployed with below properties file :

```
app.httpclient.body-expression='name='+new com.fasterxml.jackson.databind.ObjectMapper().readTree(payload).findValue('taskName').asText()+ \
'&arguments=\
--increment-instance-enabled=true \
--split-thread-core-pool-size=10 \
--interval-time-between-checks=5000 \
--composed-task-arguments=--message='+new String(T(java.util.Base64).getEncoder().encode(payload.getBytes())) 
app.httpclient.http-method=POST
app.httpclient.url=http://localhost:9393/tasks/executions
app.httpclient.headers-expression={'Content-Type':'application/x-www-form-urlencoded'}
```

I also change the `--composed-task-arguments` via different `payload` between CTR invocations : same effect.

So, my question is how should I force the CTR to run new job and not proceed the previously failed from the failed step. (This question at [SO](https://stackoverflow.com/questions/47569986/on-next-execution-ctr-proceeds-from-previously-failed-step))

**UPDATE**
Digging into spring sources, the below code from `JobLauncherCommandLineRunner::getNextJobParameters`  explains the behavior:

```java
if (isStoppedOrFailed(previousExecution) && job.isRestartable()) {
                // Retry a failed or stopped execution
                parameters = previousExecution.getJobParameters();
                // Non-identifying additional parameters can be removed to a retry
                removeNonIdentifying(additionals);
            }
            else if (incrementer != null) {
                // New instance so increment the parameters if we can
                parameters = incrementer.getNext(previousExecution.getJobParameters());
            } 
```

How do I control over job : restart previously failed or run new  instance?

**Comment by sabbyanandan** [comment] 2017-12-08 19:57
Duplicate of: https://stackoverflow.com/questions/47569986/on-next-execution-ctr-proceeds-from-previously-failed-step.

**Comment by bobg9** [comment] 2017-12-20 07:34
I also encountred this issue, is there a workaround for this?

**Comment by jvmlet** [comment] 2017-12-21 08:42
@sabbyanandan , I've ended with patching the  CTR task app with the below code , this way I'm able to run new batch even if previous job execution fails.

Please consider to expose this configuration in OTB CTR app you provide, because it looks like show stopper issue when you can't run any new job with different parameters once the execution failed.

```java
@SpringBootApplication
@Import({ComposedTaskRunnerConfiguration.class, DataFlowConfiguration.class})
@Slf4j
public class ComposedtaskrunnerTaskApplication {

    public static void main(String[] args) {
        log.info("Patch started");
        SpringApplication.run(ComposedtaskrunnerTaskApplication.class, args);
    }

    @Bean
    public BeanPostProcessor postProcessor(){
        return new BeanPostProcessor() {
            @Override
            public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
                return bean;
            }

            @Override
            public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
                if(bean instanceof FlowJob){
                    log.info("Patched");
                    FlowJob.class.cast(bean).setRestartable(false);
                }
                return bean;
            }
        };
    }
}
```

**Comment by cppwfs** [comment] 2018-01-03 18:52
There are 2 questions on this issue:

1) On first run, the job runs with run.id equals 1 and and mf1 is reported as failed , BTW, the UI shows the exit code of myFailedTask as 0 , isn't is a bug ?  
CTR is built using Spring Batch.  So if the Job execution was successful it will return a 0.  In the case above the `myFailedTask-mf1` did fail however the Job execution of the CTR was successful.  To check the status of whether the CTR Job was successful use the the Jobs Tab via the SCDF Dashboard instead of the Task Executions Tab. 

2) So, my question is how should I force the CTR to run new job and not proceed the previously failed from the failed step. 
In this case add an identifying parameter (a parameter that is not prefixed with a --), to the arguments and this will create a new Job Instance.   i.e. 
`task launch myFailedTask --arguments "--increment-instance-enabled=true --split-thread-core-pool-size=10 --interval-time-between-checks=5000 foo=bar"
 Where `foo=bar` is an identifying parameter that will create a new job instance.

**Comment by jvmlet** [comment] 2018-01-03 20:37
Thanks for the answers, according to question  #2, should I provide non-repeating  identifying parameter in order to create new job instance each time?

**Comment by cppwfs** [comment] 2018-01-03 21:33
Yes.  Else it will be considered the same Job Instance.

**Comment by cppwfs** [comment] 2018-01-03 23:43
looks like this issue is resolved.  If there is any other issues please let us know.

**Closed as completed by cppwfs** 2018-01-03 23:43 UTC
